// Generated by scripts/build-cli-topics.mjs from docs/cli-topics/*.md.
// Do not edit by hand; run `node scripts/build-cli-topics.mjs`.

export interface CliTopicSummary {
  name: string;
  description: string;
}

export const CLI_TOPIC_INDEX: readonly CliTopicSummary[] = [
  { name: "document-features", description: "Document-level output shapes: --structure tagged trees and tables, --page-labels, --attachments, --outline, --viewer state, and --layers. Use when navigation, accessibility tags, embedded files, or optional content matter." },
  { name: "flags", description: "Per-flag caveats and how to choose between overlapping structural flags for an unusual document. Use when the default extraction is not enough and more than one flag could apply." },
  { name: "formats", description: "How -f json, -f toon, and -f xml differ as contracts, the XML tag projection with its escaping markers, and the TOON encoding. Use when parsing XML or TOON instead of JSON." },
  { name: "interactive", description: "Field shapes for --form-fields, --links, and --annotations: widget types and labels, link targets, annotation flags and markup geometry. Use when a PDF's fillable boxes, clickable targets, or comments matter." },
  { name: "layout", description: "The --layout block / line / table shapes, multi-column reading order, repeated chrome, heading levels, and the --geometry span contract. Use when reconstructing structure or reading order rather than reading flat text." },
  { name: "library", description: "The processDocument() / processFile() Node.js API and the full list of exported types. Use when calling pdfvision from a Node process instead of shelling out to the CLI." },
  { name: "mcp", description: "Configuring and calling the MCP server: the three tools, response budgets, refs, and how it differs from the CLI. Only needed for shell-less hosts." },
  { name: "ocr", description: "OCR language codes and ordering, confidence, traineddata install and cache, and troubleshooting. Mandatory for non-English OCR, where language order changes the result." },
  { name: "options", description: "Every CLI option with its interactions and caveats, the order arguments are resolved in, output formats, and exit codes. Use when picking or combining flags, or when explaining an exit code." },
  { name: "schema", description: "The top-level DocumentResult, the per-page PageOverview and PageResult fields, PageQuality, and the coordinate system every bbox uses. Use when consuming -f json / -f toon / processDocument() output programmatically." },
  { name: "search", description: "The SearchMatch shape and every --search semantic: literal vs regex, normalization, which sources are searched, and the find-then-zoom loop. Use when running --search or interpreting its matches." },
  { name: "visual", description: "Shapes for --image-boxes, --vector-boxes, and --visual-regions, plus what --render-scale and --render-region do. Use when picking a figure, chart, table, or form region to render and inspect visually." },
  { name: "warnings", description: "Every pages[].warnings[] code, what fires it, what it means for the text, and the raw per-page density signals behind quality. Use when a warning needs more than its inline message." },
];
